# Taskfile.yml

# See https://nanovms.gitbook.io/ops/google_cloud for ops commands

# This taskfile will enable local building of the application, building of an
# ops image, and cloud deployment management.

version: '3'

env:
  # Need credentials for Google if using GCP
  applinux: nanoapplinux
  nativeapp: nanoappnative
  imagename: nanovms-transactions-image
  configpath: ./config/config.json
  cloud: gcp
  port: 8000

# If running with pre-set environment variables do not run the dotenv
dotenv: ['.ENV']

tasks:
  build:
    desc: build native and linux apps for running in novavms
    dir: ./app
    cmds:
      - GOOS=linux go build -o ../builds/{{.applinux}} main.go
      - go build -o ../builds/{{.nativeapp}} main.go
  run-locally:
    desc: run locally using ops
    dir: ./builds
    cmds:
      - task: build
      - ops run -p {{.port}} ./nanoapplinux &
  create-image:
    desc: create image in cloud
    dir: ./builds
    cmds:
      - ops image create {{.applinux}} -c {{.configpath}} -i {{.imagename}} -t {{.cloud}}
  delete-image:
    cmds:
      # Note: requires GOOGLE_APPLICATION_CREDENTIALS, GOOGLE_CLOUD_PROJECT, and
      # GOOGLE_CLOUD_ZONE environment variables
      - ops delete image {{.imagename}}
  create-instance:
    desc: create an instance in cloud
    cmds:
      - task: create-image
      - ops instance create {{.imagename}} -t {{.cloud}} -c {{.configpath}}
      - echo "You can access the instance at the IP listed on port {{.port}}
  delete-instance:
    desc: delete a remote instance {{.imagename}}
    cmds:
      - ops instance delete 
  list-instances:
    desc: list instances in cloud
    cmds:
      - ops instance list -t {{.cloud}} -c {{.configpath}}
  test-instance:
    desc: Test deployed cloud instance
    cmds:
      - task: create-instance
      - curl http://127.0.0.1:{{.port}}/transactions
