// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: grpcpass/proto/grpcpass.proto

package grpcpass

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int64  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Date   string `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Img    string `protobuf:"bytes,3,opt,name=img,proto3" json:"img,omitempty"`
	Title  string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Alt    string `protobuf:"bytes,5,opt,name=alt,proto3" json:"alt,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcpass_proto_grpcpass_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_grpcpass_proto_grpcpass_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_grpcpass_proto_grpcpass_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Message) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Message) GetImg() string {
	if x != nil {
		return x.Img
	}
	return ""
}

func (x *Message) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Message) GetAlt() string {
	if x != nil {
		return x.Alt
	}
	return ""
}

type MessageNumber struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int64 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *MessageNumber) Reset() {
	*x = MessageNumber{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcpass_proto_grpcpass_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageNumber) ProtoMessage() {}

func (x *MessageNumber) ProtoReflect() protoreflect.Message {
	mi := &file_grpcpass_proto_grpcpass_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageNumber.ProtoReflect.Descriptor instead.
func (*MessageNumber) Descriptor() ([]byte, []int) {
	return file_grpcpass_proto_grpcpass_proto_rawDescGZIP(), []int{1}
}

func (x *MessageNumber) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

var File_grpcpass_proto_grpcpass_proto protoreflect.FileDescriptor

var file_grpcpass_proto_grpcpass_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x67, 0x72, 0x70, 0x63, 0x70, 0x61, 0x73, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x70, 0x61, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x67, 0x72, 0x70, 0x63, 0x70, 0x61, 0x73, 0x73, 0x22, 0x6f, 0x0a, 0x07, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x69, 0x6d, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x69,
	0x6d, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x6c, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x6c, 0x74, 0x22, 0x27, 0x0a, 0x0d, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x32, 0x46, 0x0a, 0x0b, 0x58, 0x4b, 0x43, 0x44, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x37, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x58, 0x4b, 0x43, 0x44, 0x12, 0x17, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x70, 0x61, 0x73, 0x73, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x1a, 0x11, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x70, 0x61, 0x73,
	0x73, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x2e,
	0x2e, 0x3b, 0x67, 0x72, 0x70, 0x63, 0x70, 0x61, 0x73, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_grpcpass_proto_grpcpass_proto_rawDescOnce sync.Once
	file_grpcpass_proto_grpcpass_proto_rawDescData = file_grpcpass_proto_grpcpass_proto_rawDesc
)

func file_grpcpass_proto_grpcpass_proto_rawDescGZIP() []byte {
	file_grpcpass_proto_grpcpass_proto_rawDescOnce.Do(func() {
		file_grpcpass_proto_grpcpass_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpcpass_proto_grpcpass_proto_rawDescData)
	})
	return file_grpcpass_proto_grpcpass_proto_rawDescData
}

var file_grpcpass_proto_grpcpass_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpcpass_proto_grpcpass_proto_goTypes = []interface{}{
	(*Message)(nil),       // 0: grpcpass.Message
	(*MessageNumber)(nil), // 1: grpcpass.MessageNumber
}
var file_grpcpass_proto_grpcpass_proto_depIdxs = []int32{
	1, // 0: grpcpass.XKCDService.GetXKCD:input_type -> grpcpass.MessageNumber
	0, // 1: grpcpass.XKCDService.GetXKCD:output_type -> grpcpass.Message
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpcpass_proto_grpcpass_proto_init() }
func file_grpcpass_proto_grpcpass_proto_init() {
	if File_grpcpass_proto_grpcpass_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpcpass_proto_grpcpass_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcpass_proto_grpcpass_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageNumber); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpcpass_proto_grpcpass_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpcpass_proto_grpcpass_proto_goTypes,
		DependencyIndexes: file_grpcpass_proto_grpcpass_proto_depIdxs,
		MessageInfos:      file_grpcpass_proto_grpcpass_proto_msgTypes,
	}.Build()
	File_grpcpass_proto_grpcpass_proto = out.File
	file_grpcpass_proto_grpcpass_proto_rawDesc = nil
	file_grpcpass_proto_grpcpass_proto_goTypes = nil
	file_grpcpass_proto_grpcpass_proto_depIdxs = nil
}
